name: little_things
description: Little things mobile client

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  cached_network_image:  3.2.0
  firebase_auth: 3.3.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  google_maps_flutter: ^2.1.1
  google_sign_in: 5.2.4
  http: ^0.13.4
  intl: ^0.17.0
  logging: 1.0.2
  provider: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svg/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

